version: '3'

services:
  web:
    build: .
    platform: linux/amd64
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db

  db:
    platform: linux/amd64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'database1'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --sql-mode=''
    volumes:
      - ./mysql:/var/lib/mysql:rw
    user: mysql